FROM node:18.16.0-alpine

#RUN apk add curl && curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v7.27.1/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;

RUN apk update && apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@7.4.1 --activate 


RUN apk add git